project:
  type: website
  output-dir: docs

website:
  title: "Sofia Sellitto"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - portfolio.qmd
      - href: SofiaSellitto_Resume.pdf 
        text: CV

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

